import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        backgroundColor: "white",
    },
    values: {
        display: "flex",
        alignItems: "flex-end",
        backgroundColor: "white",
        marginHorizontal: 15,
    },
    date_container: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-around",
        alignItems: "center",
        width: "100%",
        padding: 15,
        marginVertical: 15,
        backgroundColor: "white",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 3.84,
    },
    date_picker: {
    },
    moneySpent: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        borderWidth: 1,
        overflow: "hidden",
        padding: 3,
        borderRadius: 9,
        borderColor: "#009966",
        borderBottomColor: "#00cca3",
        backgroundColor: "white",
    },
    moneySpent_input: {
        height: 35,
        width: 100,
        margin: 3,
        fontSize: 18,
    },
    moneySpent_text: {
        fontSize: 17,
        color: "gray",
    },
    spendTypes: {
        display: "flex",
        flexDirection: "column",
        width: "100%",
        marginVertical: 15,
        backgroundColor: "white",
    },
    spendTypesTitle: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 3,
    },
    spendTypesTitle_text: {
        marginRight: 10,
        fontSize: 18,
        color: "#737373",
        fontWeight: "500",
    },
    spendTypeList_collapsed: {
        display: "flex",
        flexDirection: "row",
    },
    spendTypeList: {
        marginTop: 10,
        marginBottom: 5,
        display: "flex",
        alignItems: "center",
    },
    spendType_view: {
        borderColor: "#00cc88",
        height: 70,
        width: 70,
        margin: 5,
        overflow: "hidden",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 8,
        borderWidth: 1,
        padding: 3,
    },
    newSpendType_title: {
        fontSize: 36,
        textAlign: "center",
        color: "green",
        fontWeight: "500",
    },
    spendType_title: {
        fontSize: 16,
        height: 20,
        textAlign: "center",
    },

    buttonSave: {
        display: "flex",
        flexDirection: "row",
        borderColor: "#00cc88",
        borderWidth: 2,
        marginVertical: 15,
        alignSelf: "flex-end",
        borderRadius: 50,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#00cc88",
        padding: 8,
    },
    buttonSave_title: {
        fontWeight: "500",
        fontSize: 18,
        marginLeft: 6,
        marginRight: 12,
    },
    note_container: {
        display: "flex",
        width: "100%",
    },
    spendDescription: {
        borderBottomWidth: 2.5,
        width: "80%",
        padding: 4,
        fontSize: 18,
        borderRadius: 2,
        borderColor: "#999999",
    },
    spendList: {
        width: "100%",
        paddingHorizontal: 15,
    },
});
